# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scrape.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scrape.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cscrape.proto\"6\n\rScrapeRequest\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.TokenType\x12\x0b\n\x03url\x18\x02 \x01(\t\":\n\x0eScrapeResponse\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.TokenType\x12\x0e\n\x06tokens\x18\x02 \x03(\t*1\n\tTokenType\x12\x0c\n\x08\x44OCUMENT\x10\x00\x12\x07\n\x03TAG\x10\x01\x12\r\n\tATTRIBUTE\x10\x02\x32\x34\n\x07Scraper\x12)\n\x06Scrape\x12\x0e.ScrapeRequest\x1a\x0f.ScrapeResponseb\x06proto3'
)

_TOKENTYPE = _descriptor.EnumDescriptor(
  name='TokenType',
  full_name='TokenType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOCUMENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TAG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ATTRIBUTE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=132,
  serialized_end=181,
)
_sym_db.RegisterEnumDescriptor(_TOKENTYPE)

TokenType = enum_type_wrapper.EnumTypeWrapper(_TOKENTYPE)
DOCUMENT = 0
TAG = 1
ATTRIBUTE = 2



_SCRAPEREQUEST = _descriptor.Descriptor(
  name='ScrapeRequest',
  full_name='ScrapeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ScrapeRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='ScrapeRequest.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=70,
)


_SCRAPERESPONSE = _descriptor.Descriptor(
  name='ScrapeResponse',
  full_name='ScrapeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ScrapeResponse.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='ScrapeResponse.tokens', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=130,
)

_SCRAPEREQUEST.fields_by_name['type'].enum_type = _TOKENTYPE
_SCRAPERESPONSE.fields_by_name['type'].enum_type = _TOKENTYPE
DESCRIPTOR.message_types_by_name['ScrapeRequest'] = _SCRAPEREQUEST
DESCRIPTOR.message_types_by_name['ScrapeResponse'] = _SCRAPERESPONSE
DESCRIPTOR.enum_types_by_name['TokenType'] = _TOKENTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScrapeRequest = _reflection.GeneratedProtocolMessageType('ScrapeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPEREQUEST,
  '__module__' : 'scrape_pb2'
  # @@protoc_insertion_point(class_scope:ScrapeRequest)
  })
_sym_db.RegisterMessage(ScrapeRequest)

ScrapeResponse = _reflection.GeneratedProtocolMessageType('ScrapeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPERESPONSE,
  '__module__' : 'scrape_pb2'
  # @@protoc_insertion_point(class_scope:ScrapeResponse)
  })
_sym_db.RegisterMessage(ScrapeResponse)



_SCRAPER = _descriptor.ServiceDescriptor(
  name='Scraper',
  full_name='Scraper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=183,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='Scrape',
    full_name='Scraper.Scrape',
    index=0,
    containing_service=None,
    input_type=_SCRAPEREQUEST,
    output_type=_SCRAPERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCRAPER)

DESCRIPTOR.services_by_name['Scraper'] = _SCRAPER

# @@protoc_insertion_point(module_scope)
